[package]
name = "distinst-external-commands"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>", "Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "External commands used by distinst and its crates"
repository = "https://github.com/pop-os/distinst"
readme = "README.md"
license = "MIT"
keywords = ["distinst", "external", "commands"]
edition = "2018"

[dependencies]
disk-types = { path = "../disk-types" }
distinst-utils = { path = "../utils" }
log = "0.4.8"
proc-mounts = "0.2.4"
rand = "0.7"
smart-default = "0.6.0"
sys-mount = "1.5.1"
tempdir = "0.3.7"
