[package]
name = "distinst"
version = "0.3.2"
description = "Distribution Installer Backend"
repository = "https://github.com/pop-os/distinst"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
license = "LGPL-3.0"
readme = "README.md"

[workspace]
members = ["cli", "ffi"]

[lib]
name = "distinst"
crate-type = ["lib"]

[dependencies]
libc = "0.2"
libparted = "0.1.2"
log = "0.3"
tempdir = "0.3"
itertools = "0.7.6"
derive-new = "0.5.0"
rand = "0.4.2"

[dependencies.failure]
version = "0.1.1"
default-features = false
features = ["derive"]

[dependencies.failure_derive]
version = "0.1.1"

[profile.release]
debug = true
