[package]
name = "distinst-disks"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>", "Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "Probe and manipulate block devices"
repository = "https://github.com/pop-os/distinst"
readme = "README.md"
license = "MIT"
keywords =  ["distinst", "disk", "management", "partition"]
categories = ["filesystem", "os"]

[dependencies]
bitflags = "1.0.4"
derive-new = "0.5.5"
disk-types = "0.1.0"
distinst-bootloader = { path = "../bootloader" }
distinst-disk-ops = { path = "../disk-ops" }
distinst-external-commands = { path = "../external" }
distinst-utils = { path = "../utils" }
envfile = "0.1.0"
failure = "0.1.3"
failure_derive = "0.1.3"
fstab-generate = "0.1.1"
itertools = "0.7.8"
libc = "0.2.43"
libparted = "0.1.3"
log = "0.4.5"
os-detect = "0.2.1"
partition-identity = "0.1.6"
proc-mounts = "0.1.0"
rand = "0.5.5"
rayon = "1.0.2"
sys-mount = "1.1.0"
sysfs-class = "0.1.1"
tempdir = "0.3.7"
